# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

## Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
RUN npm install

COPY . .
RUN npm run build

## Runner stage
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and production modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Default command
CMD ["node", "dist/index.js"]
